"""
Single source of truth for application name and version.

Import from here everywhere — GUI title, logs, copyright page via ConversionConfig.

Version resolution order:
  1. _version.py  — generated by setuptools-scm during `python -m build`
                    or by build_exe.py before Nuitka compilation.
                    Always present in a compiled Nuitka bundle.
  2. importlib.metadata — works for `pip install` / editable installs.
  3. Hard-coded fallback — bare `git clone` with no build step.
"""
from __future__ import annotations

# App name is a plain constant — never generated, never needs a fallback chain.
APP_NAME       = "FictionPub"
APP_NAME_SHORT = "fictionpub"

try:
    from ._version import __version__ as VERSION
except ImportError:
    try:
        from importlib.metadata import version as _meta_version
        VERSION = _meta_version(APP_NAME_SHORT)
    except Exception:
        VERSION = "0.0.0+unknown"